### ISSUE TITLE
Monterey Update Please 

### ISSUE THREAD

**Issue by UdemyLearner** [qiqco/Atheros-Wi-Fi-Hackintosh-macOS#1]
# Hey,
## Can you please update  

#       [AirPortAtheros40-AR9565.zip]  for Monterey

**Comment by qiqco** [comment]
目前还暂不支持

**Comment by Inscoteam** [comment]
I don't understand what you mean, is it working on Monterey, or is it asking the author to update the firmware?

**Comment by Inscoteam** [comment]
Is it to let the author update readme.md?

**Comment by Hackers-kz** [comment]
Hello. Please tell me if there is support for QCWB335 - AR9565 on Monterey
